[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/dougc333/Colab-Notebooks/blob/main/broadcast_1.ipynb)


# **Numpy, Pytorch**

<ol>
<li>(3,)</li>
<li>np.reshape() is a view, np.reshape(-1,1). the -1 means let numpy figure out the row dim, specify 1 column. </li>
<li>numpy newaxis()/squeeze() vs pytorch squeeze()/unsqueeze()</li>
<li></li>
<li></li>

</ol>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [ ]:
%cd /content/drive/MyDrive/'Colab Notebooks'
#move to Colab-Notebooks to check into git repo

/content/drive/MyDrive/Colab Notebooks


# **(3,) is a list, not a 3d array; not (3,1) or (1,3)**

In [ ]:
import numpy as np

a = np.array([1,1,0])
print(a.shape)

(3,)


# **np,dot has 2 APIs**

It figures out which operation depending on input shapes

matrix multiply: np.dot() = $\sum_N a[i]*b[i]$, output is matrix

vector dot product np.dot(), the math is exactly the same; output is scalar



In [ ]:
import numpy as np

#this is a confusing example because the matrix case is a 1d vector. They should use a 2x2
a = np.array([1,1,0])

b = np.array([-1,2,3]).reshape(-1,1)

print(a)
print(b)
print(f'a.T * b = {np.dot(a,b)}')

print("I am a vector dot product:",np.dot(np.array([1,1,1]), np.array([1,1,1]) ))

[1 1 0]
[[-1]
 [ 2]
 [ 3]]
a.T * b = [1]
3


In [ ]:
x = np.zeros((3,1,4))
y = np.ones((1,5,4))
z = x + y

print(z.shape)

(3, 5, 4)


**np.reshape()**


Multiple ways to do reshaping from row major to column major

[1,2,3] to column major [[1],
                         [2],
                         [3]]

row major shape is (1,3), column major is (3,1). The brackets in the column major format are important because it indicates 3 separate rows.

There are multiple ways to reshape a row major to column major format. The clearest but the least used is to reshape explicitly with known dimensions

np.reshape(array, shape) so to reshape a row major to column major format

a = [1,2,3]
b = np.reshape(a, (1,3))

Unfortunately this isn't what people do.

b = a.reshape(-1,1) they ignore the first dimension using -1 and specify 1 column. Numpy figures out the -1 says numpy will figure out the num rows.

This is ok but it carries into pytorch and it is necessary to practice these for formatting batches in LLMs




In [ ]:
b = np.array([-1,2,3]).reshape(-1,1)
print(b)

[[-1]
 [ 2]
 [ 3]]


**Shapes**

<ul>
<b>(3,) isn't 3 rows!!!</b>
<li>A list is 1d and shape (len, ) is neither a row or col</li>
<li>They defined a new convention which is reveresed from normal APIs</li>
<li>a = np.array([10, 20, 30]) is shape (3,)</li>
<li>Same in pytorch, b = torch.tensor([10,20,30]); torch.Size([3]) </li>
<li>both numpy and pytorch have to be resized to row,col format for a 2D matrix. </li>
<b>Adding an axis in numpy or adding a dim in pytorch</b>
<li>Numpy convert (3,) to (3,1)</li>
<li>np.reshape(np.array([1,2,3]), (3,1))</li>
<li>np.rehape(np.array([1,2,3]), (1,3))</li>
<b>np.resize() cycles through the original data if not enough elements</b>
<li>np.resize(np.array([1,2,3]), (3,1))</li>
<li>np.resize(np.array([1,2,3]), (1,3))</li>
<li>pytorch pads with 0 if not enough data in resize</li>


<b>Numpy newaxis() and squeeze() vs pytorch squeeze() and unsqueeze()</b>
<li>np.newaxis()</li>
<li>np.squeeze()</li>

<li>Pytorch convert torch.Size([3]) to torch.Size([3,1])</li>
<li></li>

<b>Remove an axis</b>
<li></li>
<b>Testing for Contiguous</b>
<li>Performance bottlenecks when data operations break contiguous memory both in CPU and GPU models</li>
<li>The normal pytorch format is (Batch, Channels, Height, Width) but CNNS require Channels last! Use tensor.to(memory_format=torch.channels_last)</li>

<b>Transpose Example</b>
<li>a.T breaks contiguouis. It is a view but it causes 2-10x slowdown when materializing the calculation</li>
<li>GPU expects (NHWC) for channels last. </li>
</ul>


In [ ]:
b_prime = np.reshape(np.array([-1,2,3]),(3,1))
print(b_prime)
# reshape is a new view, resize is a new memory layout with removed or added elements
print(---------------------------------------)

[[-1]
 [ 2]
 [ 3]]


**np.dot(), confusing**

<ul>
<b>np.dot() is a dot product or multiply if 1d  AND matmul for 2d arrays/matrices</b>
<li>a = np.ones(2,2)</li>
<li>b = 5*np.ones(2,2)</li>
<li>print(a,b)</li>
</ul>


<ul>
<b>mental model</b>
<li>$result[i,j]=\sum_{k}A[i,k]×B[k,j]$</li>
<li>First match the i,j, k indexes. There can only be one k dim which has to match the first and second matrix from matrix math rules. Match in order, (i,k,j) to avoid mistakes. </li>
<li>i=2, k=2, j=2</li>
<li>result shape =(i,j)= (2,2); </li>
<li>Iterate through the result dims. </li>
<li>result(1,1) = a(1,1)*b(1,1) + a(1,2)*b(2,1) = 1*5 + 1+5=10  </li>
<li>result(1,2) = a(1,1)*b(1,1) + a(1,2)*b(2,1) = 1*5 + 1+5=10</li>
<li>result(2,1) = a(1,1)*b(1,1) + a(1,2)*b(2,1) = 1*5 + 1+5=10</li>
<li>result(2,2) = a(1,1)*b(1,1) + a(1,2)*b(2,1) = 1*5 + 1+5=10</li>
</ul>


<ul>
<b>Matmul np.matmul(a,b) or a@b</b>
<li>Assume multi dimensions not 2dim case which np.dot handles</li>
<li>(B,T,C) convention Batch, Time, Columns. Time is rows. </li>
<li>MatMul rules (B,T,C) * (C,X). </li>
</ul>

<ul>
<b>The big issue a@b != np.dot(a,b) for dims>2</b>
<li>Why? Because np.dot doesnt broadcast but a@b does</li>
<li></li>
<li></li>
<li></li>

</ul>

<ul>
<b>CPU and GPU performance</b>
<li>CPU memory layout is row major, increment columns first for sequential cache/dram or memory access. CPU preloads data in chunks to L1 cache</li>
<li>GPU has 32 threads. Each thread should have data. </li>
</ul>




In [ ]:
# test np.dot
a = np.ones((2,2))
print(a.flags) # verify row major and not column major(fortan)
b = 5 * np.ones((2,2))
print(a)
print('------')
print(b)
print('------')
print(a*b)
print('------')
print(np.dot(a,b))


print('1d dot product same as multiply')
print(np.dot(5,6))
print('1d array dot product same as element wise multiply')
print(np.dot([1,1,1],[2,2,2]))
print('1d numpy array dot product same as elemnent wise multiply')
print(np.dot(np.array([1,1,1]),np.array([2,2,2])))


  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

[[1. 1.]
 [1. 1.]]
------
[[5. 5.]
 [5. 5.]]
------
[[5. 5.]
 [5. 5.]]
------
[[10. 10.]
 [10. 10.]]
1d dot product same as multiply
30
1d array dot product same as element wise multiply
6
1d numpy array dot product same as elemnent wise multiply
6


**Broadcasting**

Broadcasting is a numpy and pytorch feature for adjusting vector and matrix multiply dimensions beyond the standard (a,b) * (b,c) rule when there are more than 2 dims.  

Broadcasting widely used in image processing. X images, multiply each subimage with a filter will use broadcasting rules.

LLMs will use broadcasting extensively


<b>Numpy Broadcasting; vector scalar right aligned, matrix batch aligned</b>
<ul>
<li>Elements are broadcast or replicated with stride 0 trick. Use stride 0 to make it match the broadcast dimension. When computing the loop iteration pytorc and GPU replace the stride element with stride[0] which means keep on reading the current element. It doesn't allocate new memory for broadcast.  </li>
</ul>


<ul>
<b>Numpy warning. np.dot() doesn't support broadcasting, *, @ do. </b>
<li>both pytorch and numpy broadcasting don't allocate memory</li>
<li>They use a stride trick; instead of a stride of 1 they keep on reading the same element which is a stride of 0. </li>
</ul>

<b>Element wise Broadcast Rules</b>
<ol>
<li>first left pad the smaller shape then compare each dim </li>
<li>either dim ==1 or both equal, (3,1), (1,1) then dimension passes </li>
<li>Broadcast fails if neither dim ==1 and they aren't equal to each other. </li>
</ol>

<ul>
<b>Example</b>
<li>a=(2,5),b=(3,). Can we broadcast these?</li>
<li>(2,5)</li>>
<li>1) (1,3) left pad the smaller one to right align</li>
<li>Iterate through the dims</li>
<li>2) Compare 2<->1, this ok bc one of the dims is a 1</li>
<li>3) Compare 5<->3, this fails because the dims not equal and neither one is 1. </li>
</ul>

<ul>
<b>Example</b>
<li>a=(2,10),b=(10,). Can we broadcast these?</li>
<li>1) left pad. (2,10), (1,10)   </li>
<li>Iterate through the dims</li>
<li>2) compare dim 1: 2<->1, ok one dim ==1</li>
<li>3) comapare dim2: 10<->10 ok, both equal</li>
</ul>


<ul>
<b>Example</b>
<li>a=(4,3,2), b=(2,)</li>
<li>left pad (4,3,2), (1,1,2)</li>
<li>Iterate through the dims</li>
<li> 4<->1; ok </li>
<li> 3<->1; ok </li>
<li> 2<->2; ok </li>
<li>all tests pass</li>
</ul>

<ul>
<b>Example</b>
<li>a=(6,1,5), b=(3,5)</li>
<li>left pad b;a=(6,1,5), b=(1,3,5) </li>
<li>Iterate through the dims</li>
<li> 6<->1; ok, second dim is 1 </li>
<li> 1<->3; ok, first dim is 1  </li>
<li> 5<->5; ok, equal dims</li>
</ul>


<ul>
<b>Example</b>
<li>a = (4,3,2),  b= (4,2)</li>
<li>left pad b: a = (4,3,2),  b= (1, 4,2)</li>
<li>Iterate through the dims</li>
<li> 4<->1; ok </li>
<li> 3<->4; fails </li>
<li> 2<->2; ok </li>
</ul>



<b>Rules modification for matmul</b>
<ol>
<li>pytorch and numpy same</li>
<li>last 2 dims do not broadcast</li>
<li>Verify matmul, last 2 dims follow matmul rules (a,b)x(b,c); the b has to match</li>
<li>Follow earlier elementwise broacasting</li>
</ol>


<ul>
<b>Matmul broadcast Example</b>
<li>A: (3, 4), B: (2, 5, 4, 6)</li>
<li>match matrix dims B:(2, 5, 4, 6) and left pad for right alignment</li>
<li>(2, 5, 4, 6)</li>
<li>(1, 1, 3, 4)</li>
<li>Iterate through the dims</li>
<li> 2<->1; ok </li>
<li> 5<->1; ok </li>
<li> 4<->3; dont align, verify matrix rules; ok </li>
<li> 2<->1; dont align, verify matrix rules; ok </li>
<li>OK</li>
</ul>


<ul>
<b>Matmul broadcast Example</b>
<li>A: (4, 3, 5, 3, 8) B: (8, 6)</li>
<li>match matrix dims B:(2, 5, 4, 6) and left pad for right alignment</li>
<li>(4, 3, 5, 3, 8)</li>
<li>(1, 1, 1, 8, 6)</li>
<li>Iterate through the dims</li>
<li> 4<->1; ok </li>
<li> 3<->1; ok </li>
<li> 5<->1; ok </li>
<li> 3<->8; dont align, verify matrix rules; ok </li>
<li> 8<->6; dont align, verify matrix rules; ok </li>
</ul>


<ul>
<b>Matmul broadcast Example</b>
<li>A: (4,2,3,5) B: (3,2,5,6)</li>
<li>match matrix dims, no left pad needed</li>
<li>(4, 2, 3, 5)</li>
<li>(3, 2, 5, 6)</li>
<li>Iterate through the dims</li>
<li> 4<->3; fails</li>
<li> 2<->2; ok </li>
<li> 3<->5; dont align, verify matrix rules; ok</li>
<li> 5<->6; dont align, verify matrix rules; ok</li>
</ul>


<b>pytorch matrix broadcast</b>
<ul>
<li>[..., m, k]  @  [..., k, n]  →  [..., m, n]</li>
</ul>



In [ ]:
# test examples with pytorch

#Broadcast vector to scalar
print('vector scalar broadcasting')
a = np.array([1,1,1])
b = np.array([3])
print(a.shape, b.shape)
# right->left align (3,), (1,) means 1 gets expanded to 3


print('--------------')
print('matrix broadcasting')
print('careful matrix broadcasting rules different than scalar')
print('--------------')

A = np.ones((10, 3, 4))
B = np.ones((1, 4, 5))

C = A @ B
print(C.shape)

(3,) (1,)
--------------
(10, 3, 5)


# **DANGER**


<b>Numpy</b>
<ul>
<li>np.dot doesnt broadcast</li>
<li>Wont generate error messages</li>
<li>*, np.matmul(), @ broadcast</li>
</ul>

<b>pytorch</b>
<ul>
<li>torch.mm(), torch.bmm(), torch.dot() dont broadcast</li>
<li>Will generate error messages warning if dims dont match</li>
<li>@, torch.matmul() broadcast</li>
</ul>

# **np.dot() does not broadcast np.dot(a,b) != a@b**

do not use!!!

In [ ]:
# np.dot() doesnt broadcase
# * and @ are not the same for more than 2 dims because of broadcasting. np.dot() doesnt broadcast but @ does.
# np.dot considered legacy.

a = np.random.rand(3,4,2)
b = np.random.rand(2,4)
d = np.dot(a,b)
e = a@b
print('-----------')
print(d==e)

-----------
[[[ True  True  True  True]
  [ True  True  True False]
  [ True  True  True  True]
  [ True False  True  True]]

 [[ True  True  True  True]
  [False  True  True False]
  [ True  True  True  True]
  [False False  True  True]]

 [[ True  True  True  True]
  [False  True  True False]
  [ True  True  True  True]
  [ True  True  True  True]]]



# **Operations which produce (3,).**

<ul>
<li>x.mean(), center a batch. Uses broadcasting, need keepdim=True to prevent (4,). keepdim=True gives (4,1). We can unsqueeze to get same result. </li>
</ul>


In [83]:
# 1) [1,2,3]
# 2) use x.repeat() to make (B,T,C)
# 3) calculate x.mean(dim=0, keepdim=True) dim=0 is a row mean if (T,C), dim=1 is a row mean if (B,T,C).


# compute a average across all rows and subtract the mean from each entry in the row
# thsi is the lousy api but easy to remember
a = torch.tensor([1,2,3])
a_mean = torch.mean(a, dtype=torch.float32)
print(f'a_mean:{a_mean}')
a_centered = a-a_mean
print(f'a_centered:{a_centered}')

# create a batch of 4 for [1,2,3]

a_batch = a.repeat(4, 1)
print(a_batch.shape)
print("a_batch:",a_batch)

# how to traverse rows with torch.mean(), use broadcasting
# this is the more complicated api, requries a dim=X term.
# keepdim prevents (4,) which screws up broadcasting
a_mean_nodims = a_batch.mean(dim=1, keepdim=False, dtype=torch.float)
a_mean = a_batch.mean(dim=1, keepdim=True, dtype=torch.float)

#see how mean_nodims missing 1? shape is (4,)
print(a_mean_nodims.shape, a_mean.shape)

print(a_mean)
a_centered = a_batch - a_mean
print(a_centered)

a_mean:2.0
a_centered:tensor([-1.,  0.,  1.])
torch.Size([4, 3])
a_batch: tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])
torch.Size([4]) torch.Size([4, 1])
tensor([[2.],
        [2.],
        [2.],
        [2.]])
tensor([[-1.,  0.,  1.],
        [-1.,  0.,  1.],
        [-1.,  0.,  1.],
        [-1.,  0.,  1.]])



# **torch.unsqueeze(index_pos)**

Adding dim of 1 to shape. index_pos tells torch to insert at index position 0,1,2,-1 using python indexing.


torch.unsqueeze(index) inserts a 1 at index position.

torch.unsqueeze(0) inserts a 1 at dim 0, (2,2) -> 1,2,2

torch.usqueeze(1) inserts a 1 at dim 1, (2,2) -> 2,1,2

torch.unsqueeze(-1) inserts a 1 at last dim, (2,2)->(2,2,-1)



In [48]:
import torch

print(torch.ones((2,2)).unsqueeze(0).shape)
print(torch.ones((2,2)).unsqueeze(1).shape)
print( torch.ones((2,2)).unsqueeze(-1).shape)


torch.Size([1, 2, 2])
torch.Size([2, 1, 2])
torch.Size([2, 2, 1])


Test Programs; chatGPT generated. Are these useful?

In [ ]:
import torch
from typing import List, Tuple

def broadcast_shape(shape_a: Tuple[int, ...],
                    shape_b: Tuple[int, ...]) -> Tuple[int, ...]:
    """
    Compute the broadcasted shape of two tensors, or raise ValueError
    if they are not broadcastable (NumPy/PyTorch rules).
    """
    # Align from the right by prepending 1s on the shorter shape
    a = list(shape_a)
    b = list(shape_b)

    max_len = max(len(a), len(b))
    a = [1] * (max_len - len(a)) + a
    b = [1] * (max_len - len(b)) + b

    out: List[int] = []
    for dim_a, dim_b in zip(a, b):
        if dim_a == dim_b or dim_a == 1 or dim_b == 1:
            out.append(max(dim_a, dim_b))
        else:
            raise ValueError(f"Shapes {shape_a} and {shape_b} are not "
                             f"broadcastable: conflict {dim_a} vs {dim_b}")
    return tuple(out)


def explain_broadcast(shape_a: Tuple[int, ...],
                      shape_b: Tuple[int, ...]) -> None:
    """
    Print a step-by-step explanation of broadcasting between two shapes.
    """
    print(f"A shape: {shape_a}")
    print(f"B shape: {shape_b}")
    print("-" * 40)

    # Align with leading 1s
    a = list(shape_a)
    b = list(shape_b)
    max_len = max(len(a), len(b))
    a = [1] * (max_len - len(a)) + a
    b = [1] * (max_len - len(b)) + b

    print("Aligned (with leading 1s):")
    print(f"A aligned: {tuple(a)}")
    print(f"B aligned: {tuple(b)}")
    print("-" * 40)

    out: List[int] = []
    print("Compare dimensions (left → right):")
    for i, (dim_a, dim_b) in enumerate(zip(a, b)):
        pos = i - max_len  # relative from the right: -1 is last dim
        msg = f"  dim {i} (from left, pos {pos:+} from right): {dim_a} vs {dim_b} -> "
        if dim_a == dim_b:
            out_dim = dim_a
            reason = "same, keep"
        elif dim_a == 1:
            out_dim = dim_b
            reason = "A expands to match B"
        elif dim_b == 1:
            out_dim = dim_a
            reason = "B expands to match A"
        else:
            print(msg + "❌ conflict (not broadcastable)")
            print()
            print(f"Result: shapes {shape_a} and {shape_b} are NOT broadcastable.")
            return
        out.append(out_dim)
        print(msg + f"✔ {out_dim} ({reason})")

    out_shape = tuple(out)
    print("-" * 40)
    print(f"Broadcasted shape: {out_shape}")
    print()


# --------- quick tests / examples ---------
if __name__ == "__main__":
    # 1) Your classic (B,T,1) × (B,1,D)
    B, T, D = 2, 4, 8
    explain_broadcast((B, T, 1), (B, 1, D))

    # 2) (B,T,D) + (D,)
    explain_broadcast((B, T, D), (D,))

    # 3) (B,T) × (D,) – usually invalid unless T == D
    try:
        explain_broadcast((B, T), (D,))
    except Exception as e:
        print("Caught error:", e)

    # 4) Quick programmatic use:
    print("broadcast_shape((3, 1), (1, 4)) ->",
          broadcast_shape((3, 1), (1, 4)))


A shape: (2, 4, 1)
B shape: (2, 1, 8)
----------------------------------------
Aligned (with leading 1s):
A aligned: (2, 4, 1)
B aligned: (2, 1, 8)
----------------------------------------
Compare dimensions (left → right):
  dim 0 (from left, pos -3 from right): 2 vs 2 -> ✔ 2 (same, keep)
  dim 1 (from left, pos -2 from right): 4 vs 1 -> ✔ 4 (B expands to match A)
  dim 2 (from left, pos -1 from right): 1 vs 8 -> ✔ 8 (A expands to match B)
----------------------------------------
Broadcasted shape: (2, 4, 8)

A shape: (2, 4, 8)
B shape: (8,)
----------------------------------------
Aligned (with leading 1s):
A aligned: (2, 4, 8)
B aligned: (1, 1, 8)
----------------------------------------
Compare dimensions (left → right):
  dim 0 (from left, pos -3 from right): 2 vs 1 -> ✔ 2 (B expands to match A)
  dim 1 (from left, pos -2 from right): 4 vs 1 -> ✔ 4 (B expands to match A)
  dim 2 (from left, pos -1 from right): 8 vs 8 -> ✔ 8 (same, keep)
----------------------------------------
Bro

In [ ]:

B, T, D = 2, 4, 8
explain_broadcast((B, T, 1), (B, 1, D))

A shape: (2, 4, 1)
B shape: (2, 1, 8)
----------------------------------------
Aligned (with leading 1s):
A aligned: (2, 4, 1)
B aligned: (2, 1, 8)
----------------------------------------
Compare dimensions (left → right):
  dim 0 (from left, pos -3 from right): 2 vs 2 -> ✔ 2 (same, keep)
  dim 1 (from left, pos -2 from right): 4 vs 1 -> ✔ 4 (B expands to match A)
  dim 2 (from left, pos -1 from right): 1 vs 8 -> ✔ 8 (A expands to match B)
----------------------------------------
Broadcasted shape: (2, 4, 8)



In [ ]:
import torch
from typing import List, Tuple, Sequence

Shape = Tuple[int, ...]


def broadcast_shape_many(shapes: Sequence[Shape]) -> Shape:
    """
    Compute the broadcasted shape of N tensors (NumPy/PyTorch rules).

    shapes: iterable of shapes, e.g. [(B,T,1), (B,1,D), (1,T,1)]
    returns: single broadcasted shape, or raises ValueError if incompatible.
    """
    if not shapes:
        return ()

    # Step 1: compute max rank and left-pad each shape with 1s
    max_len = max(len(s) for s in shapes)
    aligned: List[List[int]] = []
    for s in shapes:
        padded = [1] * (max_len - len(s)) + list(s)
        aligned.append(padded)

    out: List[int] = []
    # Step 2: for each dimension (left → right, but rules are symmetric)
    for dim_idx in range(max_len):
        dims_here = [a[dim_idx] for a in aligned]
        non_ones = sorted({d for d in dims_here if d != 1})

        if len(non_ones) == 0:
            # all 1s → result is 1
            out_dim = 1
        elif len(non_ones) == 1:
            # all non-1 dims agree → that is the result dim
            out_dim = non_ones[0]
        else:
            # more than one distinct non-1 size → conflict
            raise ValueError(
                f"Incompatible shapes at dim {dim_idx}: {dims_here} "
                f"(non-1 dims {non_ones})"
            )
        out.append(out_dim)

    return tuple(out)


def explain_broadcast_many(shapes: Sequence[Shape]) -> None:
    """
    Verbose explanation of N-way broadcasting.
    """
    print("Input shapes:")
    for i, s in enumerate(shapes):
        print(f"  Tensor {i}: {s}")
    print("-" * 60)

    if not shapes:
        print("No shapes given → result shape is ().")
        return

    max_len = max(len(s) for s in shapes)
    aligned: List[List[int]] = []
    for s in shapes:
        padded = [1] * (max_len - len(s)) + list(s)
        aligned.append(padded)

    print("Aligned with leading 1s (so all have same rank):")
    for i, a in enumerate(aligned):
        print(f"  Tensor {i} aligned: {tuple(a)}")
    print("-" * 60)

    out: List[int] = []
    print("Per-dimension analysis (left → right):")
    for dim_idx in range(max_len):
        dims_here = [a[dim_idx] for a in aligned]
        non_ones = sorted({d for d in dims_here if d != 1})

        print(f"\nDim {dim_idx} (from left):")
        for i, d in enumerate(dims_here):
            print(f"  - Tensor {i}: {d}")

        if len(non_ones) == 0:
            out_dim = 1
            print("  -> All dims are 1 → result dim = 1")
        elif len(non_ones) == 1:
            out_dim = non_ones[0]
            expanders = [
                i for i, d in enumerate(dims_here) if d == 1 and out_dim != 1
            ]
            print(f"  -> Non-1 dims agree on {out_dim} → result dim = {out_dim}")
            if expanders:
                print(f"     Tensors {expanders} broadcast (their dim 1 expands)")
        else:
            print(
                f"  -> ❌ Conflict: multiple distinct non-1 dims {non_ones}. "
                f"Shapes are NOT broadcastable."
            )
            return

        out.append(out_dim)

    out_shape = tuple(out)
    print("\n" + "-" * 60)
    print(f"Broadcasted shape: {out_shape}")
    print()


# --------------------------
# Example usage / quick tests
# --------------------------
if __name__ == "__main__":
    B, T, D = 2, 4, 8

    # 1) Classic attention-style shapes: (B,T,1) * (B,1,D) * (1,T,D)
    shapes1 = [(B, T, 1), (B, 1, D), (1, T, D)]
    explain_broadcast_many(shapes1)
    print("broadcast_shape_many:", broadcast_shape_many(shapes1))
    print()

    # 2) (B,T,D) + (D,) + (1,1,D)
    # (D,) is the same as
    shapes2 = [(B, T, D), (D,), (1, 1, D)]
    explain_broadcast_many(shapes2)
    print("broadcast_shape_many:", broadcast_shape_many(shapes2))
    print()

    # 3) Incompatible case: (B,T) and (D,2)
    shapes3 = [(B, T), (D, 2)]
    try:
        explain_broadcast_many(shapes3)
        print("broadcast_shape_many:", broadcast_shape_many(shapes3))
    except ValueError as e:
        print("Caught error:", e)

Input shapes:
  Tensor 0: (2, 4, 1)
  Tensor 1: (2, 1, 8)
  Tensor 2: (1, 4, 8)
------------------------------------------------------------
Aligned with leading 1s (so all have same rank):
  Tensor 0 aligned: (2, 4, 1)
  Tensor 1 aligned: (2, 1, 8)
  Tensor 2 aligned: (1, 4, 8)
------------------------------------------------------------
Per-dimension analysis (left → right):

Dim 0 (from left):
  - Tensor 0: 2
  - Tensor 1: 2
  - Tensor 2: 1
  -> Non-1 dims agree on 2 → result dim = 2
     Tensors [2] broadcast (their dim 1 expands)

Dim 1 (from left):
  - Tensor 0: 4
  - Tensor 1: 1
  - Tensor 2: 4
  -> Non-1 dims agree on 4 → result dim = 4
     Tensors [1] broadcast (their dim 1 expands)

Dim 2 (from left):
  - Tensor 0: 1
  - Tensor 1: 8
  - Tensor 2: 8
  -> Non-1 dims agree on 8 → result dim = 8
     Tensors [0] broadcast (their dim 1 expands)

------------------------------------------------------------
Broadcasted shape: (2, 4, 8)

broadcast_shape_many: (2, 4, 8)

Input shapes

**Pytorch tensor practice**

[build gpt in code karpathy](https://www.youtube.com/watch?v=kCc8FmEb1nY)

In [84]:
!wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt

--2025-12-31 00:03:38--  https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1115394 (1.1M) [text/plain]
Saving to: ‘input.txt’

input.txt           100%[===================>]   1.06M  --.-KB/s    in 0.1s    

2025-12-31 00:03:38 (9.34 MB/s) - ‘input.txt’ saved [1115394/1115394]



In [93]:
with open('input.txt', 'r') as f:
  text = f.read()

len(text)
chars = set(text)
len(chars)
print("".join(chars))

stoi = {char:idx for idx, char in enumerate(chars)}
itos = {idx:char for idx, char in enumerate(chars)}

encode = lambda s:[stoi[c] for c in s] #encoder
decode = lambda l: "".join(itos[i] for i in l) #decoder

print(encode("hi"))
print(decode(encode("asdf")))

# GPT2 tokenizer

EuLMOsQftNgD$!:lBXYijFnUe&Ch,VGmK.x;dwWRSqJ3ko-AvZ?Tpz Icr'ay
bHP
[27, 19]
asdf
